### ISSUE TITLE
Missing dirt corner at spawn

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/maps#110]
![image](https://user-images.githubusercontent.com/20344300/182018770-598ede85-8d09-45a9-843b-a3ca9f58d798.png)

**Comment by SoulyVEVO** [comment]
how about updating this whole troll design and filling these ugly gaps

**Comment by ChillerDragon** [comment]
> how about updating this whole troll design and filling these ugly gaps

yea that could be done
