### ISSUE TITLE
Overpowered afk spot in fokko base

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/maps#114]
![screenshot_2022-08-05_06-24-33](https://user-images.githubusercontent.com/20344300/183001283-62ff5f1a-4bf5-4662-8714-964fc5f3ce9c.png)

I would not know how to raid that. Imo there should be no spot that can't be raided if the defender is afk. But especially none with an farmtile and portal ammo. This needs a nerv.

**Comment by fokkonaut** [comment]
I will do something about it

**Comment by ChillerDragon** [comment]
Okay since portal is free for all that is a option. But still a bit strong if portal is needed. Also if the door down there is closed boating is an option too but it requires like 6+ tees

**Comment by cyberfig** [comment]
gonna prank chiller when he closes the issue :trollface:

**Comment by fokkonaut** [comment]
> gonna prank chiller when he closes the issue :trollface:

i think this was meant to be changed again, because it makes that area more interesting.

**Comment by ChillerDragon** [comment]
![screenshot_2023-11-05_11-11-00](https://github.com/DDNetPP/maps/assets/20344300/918d7fc8-9a36-4ab3-a1fa-c2df8d5c7b3f)

It currently looks like this. @fokkonaut you want it be harder to reach again right? Any ideas on how exactly it should look?

**Comment by Arylz** [comment]
> ![screenshot_2022-08-05_06-24-33](https://user-images.githubusercontent.com/20344300/183001283-62ff5f1a-4bf5-4662-8714-964fc5f3ce9c.png)
![20240123201832_1](https://github.com/DDNetPP/maps/assets/157623379/6bf53f60-bce2-4277-8801-d594a3b20da0)
impossible

**Comment by ChillerDragon** [comment]
I am not following sorry. @Arylz could you elaborate? :)

**Comment by Arylz** [comment]
Cant raid without portal gun/

**Comment by ChillerDragon** [comment]
> Cant raid without portal gun/

If you have 3 tees and two have laser that should work easily. One is on the edge where you are in your screenshot. The other one gets dragged onto the speedups and the last who dragged him does a laser chain. The one one the speedups attacks the nader.

![blmapchill_raid](https://github.com/DDNetPP/maps/assets/20344300/562c8d52-1dbe-467e-bef4-5307fec28bff)

The same technique can be used to instantly unfreeze instead of attacking.

It is not impossible and it is not safe to afk there. But raiding this base when it is actively defended is quite hard yes.
