### ISSUE TITLE
Some stuff for next version

### ISSUE THREAD

**Issue by fokkonaut** [DDNetPP/maps#144]
- add missing freeze game tile in ancient ruin: 
![image](https://github.com/DDNetPP/maps/assets/35420825/fdc9135d-bfff-4ef2-bd79-23b07e4610d2)

- add no-bonus area in jail_release tile

- i think i had something else in mind aswell

**Comment by Roolpo** [comment]
u should add in outside of the borders between the tavern and the island u should add hmm u should add like a aaaa a  aaaaaaaaa                                          flying police that the police we have in the blmapchill but in the air because in underground is a bit sucks
