### ISSUE TITLE
[Idea] Make platforms in police 3 tiles wide instead of 2

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#17]
![Inked97807104-3e711000-1c5f-11eb-9310-6d2737e4146b_LI](https://user-images.githubusercontent.com/61762251/97807493-82fdab00-1c61-11eb-8427-20be7a30012b.png)

I think it would make fights better because there are no freeze tiles down there, it gets kinda weird when both players fall down.
Not sure if that wouldnt break police bot.

**Comment by SoulyVEVO** [comment]
i wanted to make this issue like a month ago but i forgot :p

**Comment by ChillerDragon** [comment]
As mentioned on irc this is intended to make it less cluttered and the lower area a bit safer to chill.
