### ISSUE TITLE
Rework new police area a bit

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#18]
I like the idea of deepfreeze but i think its too op for portal users and that unportal tile could be placed in marked spot.

I also think that taking other players to undeep and taking them out is a but annoying especially with high amount of players so i would suggest redesigning it to something simmilar to the picture.

![ss](https://user-images.githubusercontent.com/61762251/97926209-0a7f1300-1d63-11eb-8d32-919eda82a842.png)

**Comment by ChillerDragon** [comment]
Thanks for the feedback and a rework is actually planned details are not sure yet.

**Comment by ChillerDragon** [comment]
#20

**Comment by fokkonaut** [comment]
Close?
