### ISSUE TITLE
Extend platforms in plot area

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#19]
![image](https://user-images.githubusercontent.com/61762251/97926654-c6404280-1d63-11eb-95e2-2c5c88eb2b89.png)
Currently its really hard to move around this area, and its really annoying when you started to edit plot and every player gets stacked on top of each other on one tile. I would suggest extending it by 2 tiles so it will be easier to move around.

**Comment by ChillerDragon** [comment]
![screenshot_2020-11-03_13-25-31](https://user-images.githubusercontent.com/20344300/97986057-6c7a5f80-1dd9-11eb-831a-7f1a337f45c9.png)

Extending by one already looks a bit meh. It is intended for feel and look to have it short. But also gameplay wise it should be a bit annoying if the door is closed. I also thought about adding hook but not too sure.

**Comment by fokkonaut** [comment]
Its good like it is I think.
