### ISSUE TITLE
confusing design

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#44]
Depending on the map part sometimes yellow tiles act as hookables and sometimes as unhookables, same goes for grey tiles.

![screenshot_2021-03-09_03-50-46](https://user-images.githubusercontent.com/61762251/110412698-e626a080-808c-11eb-9c2d-059ea732db44.png)
![screenshot_2021-03-09_03-50-49](https://user-images.githubusercontent.com/61762251/110412700-e6bf3700-808c-11eb-8c91-8c0dd3170d9f.png)
![screenshot_2021-03-09_03-51-06](https://user-images.githubusercontent.com/61762251/110412701-e757cd80-808c-11eb-9d40-7749f0296582.png)
![screenshot_2021-03-09_03-51-08](https://user-images.githubusercontent.com/61762251/110412702-e757cd80-808c-11eb-90ca-bf55e165100d.png)
![screenshot_2021-03-09_03-51-49](https://user-images.githubusercontent.com/61762251/110412704-e757cd80-808c-11eb-83a4-06121daea8e4.png)
![screenshot_2021-03-09_03-51-51](https://user-images.githubusercontent.com/61762251/110412706-e7f06400-808c-11eb-96c7-516be509e0b3.png)

**Comment by fokkonaut** [comment]
Yeah, known. I think changing this will destroy the look of BlmapChill tho, I would keep it this way.

**Comment by ChillerDragon** [comment]
Yea I agree and I wish it was different. In a classical sense no generic should be hookable but that is not very common in ddrace/block maps. Anyways I am aware of the issue and I try to fix some suddle issues here and there. Always with a big backlash from @fokkonaut and a few users. But yea changing that would almost create a new map. So there is no plan on fully fixing it.
