### ISSUE TITLE
Sun beams visible through the sun

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#48]
Maybe hardly noticable but sun has different alpha values (none are set to 255) on each corner and because of that the sun beams are slightly going through the sun itself.
Not a big issue though.

**Comment by ChillerDragon** [comment]
I think pepe did the sun. I am fine with the rays being visible tho. Any hard feelings on this? Otherwise I would close the issue.

**Comment by SoulyVEVO** [comment]
> I think pepe did the sun. I am fine with the rays being visible tho. Any hard feelings on this? Otherwise I would close the issue.

Since i realized that it just makes me feel uncomfortable when i look at that sun

**Comment by fokkonaut** [comment]
> I think pepe did the sun. I am fine with the rays being visible tho. Any hard feelings on this? Otherwise I would close the issue.

just fix it?

**Comment by sss75m4** [comment]
i guess chillerdragon is lazy lol

**Comment by SoulyVEVO** [comment]
@ChillerDragon when fix
