### ISSUE TITLE
Mark non solid tiles

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#49]
Basically the map contains a lot of those hidden tiles which appear like normal but you can go through them to access specific locations, i think that its confusing and forces players to use entities, its also unadvantage for players without clients which support entities (like people with vanilla 0.7), so the idea is to mark them somehow to stand out.

**Comment by ChillerDragon** [comment]
Yes I was thinking of half tiles or similar to indicate them visually not sure yet.

**Comment by Simon0316** [comment]
what about the buttons in supperroom? without enteties u cant really use them. maybe replace the white circles with numbers?

**Comment by SoulyVEVO** [comment]
> what about the buttons in supperroom? without enteties u cant really use them. maybe replace the white circles with numbers?

This would also be a good change

**Comment by ChillerDragon** [comment]
> what about the buttons in supperroom? without enteties u cant really use them. maybe replace the white circles with numbers?

white circles?

**Comment by SoulyVEVO** [comment]
> > what about the buttons in supperroom? without enteties u cant really use them. maybe replace the white circles with numbers?
> 
> white circles?

i think he meant the little circle icons that mark the switch tiles, he wants to add the numbers there so its easier to indentify what switch does what

**Comment by ChillerDragon** [comment]
![screenshot_2021-03-19_22-35-17](https://user-images.githubusercontent.com/20344300/111844486-69ed5200-8903-11eb-82e6-d425a4823277.png)

There are already yellow numbers next to it. Its just missing the numbers at the actual switchers but that would not look good.

**Comment by SoulyVEVO** [comment]
seems like its closed by #65

**Comment by ChillerDragon** [comment]
Oh right. Good catch thanks :)
