### ISSUE TITLE
Kill tiles balance

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#50]
Currently kill tiles aren't easly accessible for normal players but are easy to access for people with portal which i found really abusive. While using portal people can teleport you straight to kill tiles without worring that you will get unfreezed halfway.

My idea is either to add more kill tiles and make them easy to access for everyone or remove them completly (including blocking the way to map border kill tiles)

**Comment by ChillerDragon** [comment]
Your approaches sound a bit drastic. Kill tiles everywhere or nowhere is a big change. I tried to make the portal spike at least somewhat faily with the deep https://github.com/DDNetPP/maps/pull/29 but @fokkonaut told me to revert it.

But yes you are right on a server with portal and non portal users the spike situation can get frustrating for non portal users.

**Comment by ChillerDragon** [comment]
closed by https://github.com/DDNetPP/maps/pull/66 (killtiles gone)
