### ISSUE TITLE
Mark farm tiles

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#51]
Maybe use the bronze tiles to mark which tiles are used for farming.
Most farm tiles have a specific chair like shape but i still found it pretty confusing and again as with #49 its a small disadvantage for non entities players.
![a](https://user-images.githubusercontent.com/61762251/113139953-0e3a9700-9228-11eb-85c2-d0f36d22f5af.png)

**Comment by ChillerDragon** [comment]
Ugly color. And all shapes should be clear.
