### ISSUE TITLE
Bad block gameplay at special finish

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/maps#52]
Never ending fights until one makes an ugly mistake.

![screenshot_2021-03-31_16-01-08](https://user-images.githubusercontent.com/20344300/113141251-c1f05680-9229-11eb-9456-d3e1b4db677f.png)
![screenshot_2021-03-31_16-01-17](https://user-images.githubusercontent.com/20344300/113141256-c3ba1a00-9229-11eb-9fbe-09893aa463bf.png)

**Comment by SoulyVEVO** [comment]
ye, some rework of that area would be great
