### ISSUE TITLE
Make use of large boring area on the right of the spawn

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#53]
![screenshot_2021-03-31_13-57-01](https://user-images.githubusercontent.com/61762251/113141012-7342bc80-9229-11eb-86f1-405b2ccbddeb.png)
Nothing but a long and repetitive path leading to a small island with farm tiles, i think that we could do something interesting with it.

**Comment by ChillerDragon** [comment]
I see ur point. But believe it or not xd this path is ment to be boring and i held my self back bloating something in there. But sure if there is something we really need we might place it there. But just for the sake of having something I do not really see the point. Sets focus on the wrong point of the map. This island is for players that want to be alone. So no curious travelers coming by that jumps from exciting platform to the other.

The island it self on the other hand really should be changed.

I really like the feel of the island but i wish it had better block gameplay. Having a fight there is a pain in the ass. But I have no idea on how to keep it cozy as it is and add proper block gameplay.

**Comment by SoulyVEVO** [comment]
oh wow he changed it :O
