### ISSUE TITLE
New police entrance

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/maps#60]
![screenshot_2021-04-28_18-10-01](https://user-images.githubusercontent.com/20344300/116437217-83ac7e00-a84d-11eb-9f45-55330a435e24.png)

Not sure how exactly it should look but somewhat similar to the screenshot I guess.

**Comment by fokkonaut** [comment]
I'm okay with that but would probably want to add something there. Send me the map file please

**Comment by ChillerDragon** [comment]
@fokkonaut I think the general idea could be nice but I do not see any specific implementation that is acceptable. Anyways here is the map file https://github.com/ChillerTW/GitMaps/blob/master/BlmapChill/BlmapChill_fork_a001.map

**Comment by TruePvP** [comment]
> ![screenshot_2021-04-28_18-10-01](https://user-images.githubusercontent.com/20344300/116437217-83ac7e00-a84d-11eb-9f45-55330a435e24.png)
> 
> Not sure how exactly it should look but somewhat similar to the screenshot I guess.

Wouldnt this make police like quite impossible to defend with 3 passage ways u can go through?

**Comment by ChillerDragon** [comment]
Not impossible but way harder for sure. Yea thats one of the reasons why I closed this issue and threw away the idea.
