### ISSUE TITLE
Fix infhook portal cut

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#72]
Perfect corner portal shot allows players to place portal below infhook room tele
![1](https://user-images.githubusercontent.com/61762251/131477439-d1033dda-65bf-44ef-be1f-494f8b19ac2b.png)
By doing a double nade jump they can get enough speed to fly up to that tele since portal preserves the players speed

I havent tried but same thing can be probably done by shooting portal through this door
![2](https://user-images.githubusercontent.com/61762251/131478021-f7df2d96-2935-49b8-9a91-94b64695faf8.png)

best would be to somehow block portal on both of those places

**Comment by fokkonaut** [comment]
the bottom one is not possible and the top one is known but can be easily blocked

**Comment by ChillerDragon** [comment]
https://github.com/DDNetPP/maps/pull/70 introduced a new way of annoying portal users doing the edge from the race

**Comment by ChillerDragon** [comment]
The edge was not left intentional but its known and tolerated now.
