### ISSUE TITLE
blampchill suggestion: remake the plots

### ISSUE THREAD

**Issue by sss75m4** [DDNetPP/maps#81]
in my opinion the current plots kind of suck, they are a bit too squareish and flat, so i think that it should be in more shapes and farm tile placements
heres an example image of what im thinking:
![daplots](https://user-images.githubusercontent.com/47678516/149638772-e2498494-3b19-4197-a11d-ad3122d3968f.png)

and i also think that its a bit odd that some of the big plots have less farm tiles than the small plots (plot 2 and 4)

**Comment by itubetw** [comment]
If chillerdragon changed that, it would certainly be great.

**Comment by fokkonaut** [comment]
all fine like it is.

**Comment by itubetw** [comment]
> all fine like it is.

Always the same thing gets boring

**Comment by ChillerDragon** [comment]
I agree with @fokkonaut here. Having simple squares as plot spaces is clean and easy and it works well.
