### ISSUE TITLE
BlMapChill Suggestion: delete this Platform 

### ISSUE THREAD

**Issue by itubetw** [DDNetPP/maps#82]
![Screenshot_20220115_230716](https://user-images.githubusercontent.com/91550686/149639234-385251f2-e2ad-4dc2-b496-3708987b9360.jpg)
Deletes the platform. It would be better to perform tricks as you can hook directly on the left

**Comment by cyberfig** [comment]
close this issue? afaik literally no one cares about this

**Comment by ChillerDragon** [comment]
yea sorry i like the platform closing this
