### ISSUE TITLE
Fix new spawn wayblock

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/maps#83]
![image](https://user-images.githubusercontent.com/20344300/151251030-5893f733-76f1-4a32-b979-741ba45c18fd.png)

Reduce passive wayblock that can not be combated at spawn. Add possibility to drop directly into police using some crazy ass hook for solo no weapons raiders.

Make it impossible to trap players at spawn by solo wayblocking. The spawn area should have also winnable fights due to kills. The map should not allow wayblockers to be unkillable and instantly respawn to re trap others. 

Spawn should be easy to escape even if someone decides to wayblock at spawn.
Police should be accessible without portal or laser to reduce bonus depdencys.

**Comment by ChillerDragon** [comment]
Something like this


https://user-images.githubusercontent.com/20344300/151444845-30ad0c1a-7f78-4b06-8a81-eca0fb1353fe.mp4

**Comment by itubetw** [comment]
It's pretty cool I like it but you can way block there too. And that's so easy to way block there.

**Comment by itubetw** [comment]
![Screenshot_20220128_112025.jpg](https://user-images.githubusercontent.com/91550686/151530494-9b2ec738-dcd8-4546-aa9d-a8cea145182a.jpg)

**Comment by itubetw** [comment]
Falco641: it would be too easy for randoms with full bonus to get in and out

**Comment by ChillerDragon** [comment]
> Falco641: it would be too easy for randoms with full bonus to get in and out

Yea but imo its way more faily to jetpack or infjump through there instead of self taser the old way.

And yea have to think about that fat wb

**Comment by Falco641** [comment]
> 

Not really, there's a lot of free space in the drop spot, making it easy to jetpack thru, unless the space would be tighter
