### ISSUE TITLE
Remove unfreeze in tele to edgehook room

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/maps#85]
![screenshot_2022-02-03_19-27-29](https://user-images.githubusercontent.com/20344300/152405694-c47e5a7a-1f8f-4701-825d-6cfd9252d1f8.png)

**Comment by Emilcha** [comment]
this unfreeze should be kept, otherwise blocking the room would be way easier and fight them would be only possible with the portal gun

**Comment by ChillerDragon** [comment]
as discussed with @fokkonaut  will stay
