### ISSUE TITLE
Hookthrough block inconsistencies

### ISSUE THREAD

**Issue by sss75m4** [DDNetPP/maps#86]
These hookthroughs are purple:
![aa2](https://user-images.githubusercontent.com/47678516/152620307-c562a499-6e96-4931-a03a-1be090b47327.PNG)
![aa](https://user-images.githubusercontent.com/47678516/152620313-526fbaf4-abe0-4b2b-a1fa-653e17b1519d.PNG)

These hookthroughs are red but in "4 small blocks": 
![ab](https://user-images.githubusercontent.com/47678516/152620352-1969bd20-55f3-49ce-90b2-369141a641ee.PNG)
![ab2](https://user-images.githubusercontent.com/47678516/152620355-883f58a3-175c-4a82-8f4d-0269375e0cad.PNG)

And this one seems to slightly lighter than normal:
![wtf](https://user-images.githubusercontent.com/47678516/152620389-f2e61a49-4347-4ab9-a9a8-abe7dc4d23d6.PNG)

The rest of hookthroughs are red and in "1 normal block"

**Comment by fokkonaut** [comment]
Doesnt matter, oldschool artifacts + different designs are cool :)

**Comment by ChillerDragon** [comment]
> Doesnt matter, oldschool artifacts + different designs are cool :)

No hard feelings on this one from my side. Your call. Fix or close?

**Comment by fokkonaut** [comment]
Close
