### ISSUE TITLE
Fix flappy pushing afk people into freeze in left of police

### ISSUE THREAD

**Issue by Falco641** [DDNetPP/maps#93]
![image](https://user-images.githubusercontent.com/90838137/160859227-a4ae0371-4f37-478b-825f-ff605fc8d25e.png)
flappy dont give a crap about people standing in the circled areas when he tryna get to police

**Comment by itubetw** [comment]
It is because there is not police

**Comment by ChillerDragon** [comment]
This Repository is for maps only. flappy is not part of the map. He is part of the server side modification. So this issue either belongs to [ddnet++](https://github.com/DDNetPP/DDNetPP/issues) or [F-DDrace](https://github.com/fokkonaut/F-DDrace/issues) where flappy is implemented.
