### ISSUE TITLE
Too much deep freeze in spike room.

### ISSUE THREAD

**Issue by TimePause3D** [DDNetPP/maps#94]
In my opinion there is a lot of deepfreeze tiles and it really doesnt look nice. What do you think about placing only one tile of deep freeze right here? (red circle):
Also alternative way is to make it anti-portal (blue circle)
![image](https://user-images.githubusercontent.com/85745286/162631790-f4cde299-4fc6-4d52-a186-d6a1ced2cf42.png)

It would also make spiking a lot harder, which I think that should be difficult.
What do you think about this?

**Comment by Adil33212** [comment]
ok

**Comment by ChillerDragon** [comment]
If the deep is that far in Portal can be used to directly place a tee in there. And I covered it all in deep because I thought it looks nice. Also gameplay wise its nice that deeping is easier than spiking.

Thanks for the suggestion. But I will decline that sorry.
