### ISSUE TITLE
Draft: new spawn

### ISSUE THREAD

**Issue by ChillerDragon** [DDNetPP/maps#99]
https://user-images.githubusercontent.com/20344300/173866887-0e2ffbc1-1fbe-4bbc-97df-b2388f727f56.mp4

![screenshot_2022-06-15_17-29-48](https://user-images.githubusercontent.com/20344300/173866946-1ec3bffb-7370-43d7-a7e6-57381c42fc39.png)
![screenshot_2022-06-15_17-29-45](https://user-images.githubusercontent.com/20344300/173866962-e72f8729-f679-456a-b34d-bb3bd7fd4288.png)

It is still a working version. Details and design have to be polished. But the overall structure will stay like this.
Solves a bunch of wayblock / spawnblock issues. Adds way more flow/fun to respawning. Allows for raiding police solo without laser/taser/portal -> embracing 2j gameplay.

**Comment by TimePause3D** [comment]
I really dont like this spawn at all. In my opinion, the spawn we have right now  is much better, because:
- This spawn u showed can completely ruin the "no randoms" rule in police. The new way you presented is much easier comparing to the laser trick, which means much more people will know how to enter police and thats not good at all. I'm sure there are better ways to embrace 2j gameplay c:
- The new way to leave spawn is okay, but I dont really understand it.  Where is the shop? where is the clock? (xd)

I think it would be better to open a hole under spawn and add some structures below like you did
![image](https://user-images.githubusercontent.com/85745286/174104851-10e37b7d-bb08-4a45-9f63-eb6b23722c22.png)

And let's not make police much easier accessible c:

But I still wanna see more polished version of this spawn, so keep up the work 👍

**Comment by BulgarianTee** [comment]
The spawn displayed in the video is too open, making it easy for people with bonuses to have an unfair advantage against newly spawned tees.

When people spawn in the air and fall down, it will be chaos because they will want to go in different directions. It will be a nightmare to navigate this new spawn, and it's possible that total chaos will ensue.

The new quick way into police is way too quick, which makes raiding easier. If police has the strongest farm, it should be the "hill" on the map, which should be easy to defend and hard to attack. Also imagine how many people will push themselves around for this quick method to enter police..

These are, I think, the main issues with the given design. However, as TimePause has stated, a new, a little upgraded spawn that could prevent wayblocking is a nice idea.

**Comment by ChillerDragon** [comment]
https://user-images.githubusercontent.com/20344300/174130253-040d21ae-8d1a-4507-8dac-7194c7bcc4de.mp4

I really want to fix this wb.

> When people spawn in the air and fall down, it will be chaos because they will want to go in different directions. It will be a nightmare to navigate this new spawn, and it's possible that total chaos will ensue.

Should not matter too much if you want to go down. Gravity is on your side. It should be way faster and easier to escape spawn now also when its crowded.

**Comment by ChillerDragon** [comment]
> The new way to leave spawn is okay, but I dont really understand it. Where is the shop? where is the clock? (xd)

![screenshot_2022-06-16_19-44-01](https://user-images.githubusercontent.com/20344300/174133561-99bf3173-b06b-4e93-9a5c-3383627c7622.png)

**Comment by ChillerDragon** [comment]
https://user-images.githubusercontent.com/20344300/174136739-f281ccd1-99e3-48a3-bba6-c7db0aa870b7.mp4

I made it harder to enter police without laser now. Hard to tell without seeing it rolled out for a while. But I would claim this is harder than the laser one. The swing might look easy. But getting the height correct is not that trivial.

Also it can be blocked with the switcher that used to close the spawn and there can be a wayblocker hooking through the wall. This should for sure keep unwanted randoms out.

**Comment by BulgarianTee** [comment]
> Should not matter too much if you want to go down. Gravity is on your side. It should be way faster and easier to escape spawn now also when its crowded.

If a few dead/afk tees stack up on the platform below or if a couple of people reset at the same time, chaos is inevitable. Making spawn airborne just decreases the players' control in an area where you'd think control should depend mostly on the player.

> Also it can be blocked with the switcher that used to close the spawn and there can be a wayblocker hooking through the wall. This should for sure keep unwanted randoms out.

Having switches/buttons outside of spawn or the "inner part" of the map, as i call it, feels unnatural. Always felt like they control the players in the spawn, keeps them inside or helps them to navigate it, to super room or to endless. Why are there no switches in super room to close infinite jumps? Besides, it is not worth to get the spawn blocking button anymore, if it only closes that part of the map.

> I made it harder to enter police without laser now.
The point is not to be "harder". For police to be defended it is important that there are few entrances to it, and they should be easy to defend. Now the player is not passing any freeze to enter police, which is undefendable. This entrance protects police only with a skill gap, which with time will be passed, just like with the laser trick. Before it was regarded a hard trick, and most people stuck to tasering themselves, even with limited ammo, but now everybody is doing it. The difference is that it takes time to reach the entrance, and the player has to pass through freeze, while with this entrance it is almost instant and has no freeze.

**Comment by fokkonaut** [comment]
Also a jetpack entrance

**Comment by fokkonaut** [comment]
i like the idea in general but would like to map something based on this

**Comment by ChillerDragon** [comment]
![screenshot_2022-06-18_22-03-03](https://user-images.githubusercontent.com/20344300/174455519-fd9557f5-bac3-4208-8758-376151a47c1c.png)

Made spawn a bit more closed again. Add the closing spawn switchers back. Made the bank more accessible again.

**Comment by ChillerDragon** [comment]
![screenshot_2022-06-18_22-05-03](https://user-images.githubusercontent.com/20344300/174455587-5cef73b1-b0f3-471a-901e-d2710c202161.png)
![screenshot_2022-06-18_22-05-07](https://user-images.githubusercontent.com/20344300/174455590-c3a1d290-5781-49b5-86f9-4765b908c34a.png)
![screenshot_2022-06-18_22-06-10](https://user-images.githubusercontent.com/20344300/174455593-6e89465c-98bf-497f-aa22-0a2a56f843a7.png)

**Comment by fokkonaut** [comment]
![image](https://user-images.githubusercontent.com/35420825/174502194-7f76ac94-e9b6-4097-a769-6cbd9a8b3a41.png)

entities mismatch: 
![image](https://user-images.githubusercontent.com/35420825/174502207-34f98b97-2206-40aa-90b3-877e8b672e5b.png)

**Comment by fokkonaut** [comment]
![image](https://user-images.githubusercontent.com/35420825/174502847-9cff6ce0-a9a6-4d05-8d3c-66d906f6c30c.png)

also the clock is not really in the middle, unpleasing a bit :) otherwise i like this state and also the wall to adjust is perfect for grenade jump up :)

**Comment by fokkonaut** [comment]
i figured this might still work, and yes, it does :)
https://streamable.com/vodqel

**Comment by fokkonaut** [comment]
I made a very small change which you can see in this video, which is quite nice i think. also i showed the grenade jump i pointed out earlier

(remove .txt ending, github doesnt allow .map)
[BlmapChill.map.txt](https://github.com/DDNetPP/maps/files/8936557/BlmapChill.map.txt)
r

**Comment by ChillerDragon** [comment]
> also the clock is not really in the middle, unpleasing a bit :)

Isn't the clock yours? I just moved it.

**Comment by fokkonaut** [comment]
> > also the clock is not really in the middle, unpleasing a bit :)
> 
> Isn't the clock yours? I just moved it.

No, you changed it

**Comment by ChillerDragon** [comment]
> > > also the clock is not really in the middle, unpleasing a bit :)
> > 
> > 
> > Isn't the clock yours? I just moved it.
> 
> No, you changed it

**Comment by ChillerDragon** [comment]
> > > also the clock is not really in the middle, unpleasing a bit :)
> > 
> > 
> > Isn't the clock yours? I just moved it.
> 
> No, you changed it

Indeed two tiles were lower. Got lost in the move. Fixed.

**Comment by itubetw** [comment]
> I made a very small change which you can see in this video, which is quite nice i think. also i showed the grenade jump i pointed out earlier
> https://streamable.com/fe5cpf
> (remove .txt ending, github doesnt allow .map)
> [BlmapChill.map.txt](https://github.com/DDNetPP/maps/files/8936557/BlmapChill.map.txt)
> 

Leave the spawn as it is. Way block is a part of block that plays a lot of role. And if you change spawn then please do not pack such useless things in, no one will use the shit left. If you want to go to the bank with 2j you just kill huh? That just cuts off the server. Listen to the comminuty THAT plays daily on the map. Who would like a bad map that they don't like?

**Comment by fokkonaut** [comment]
You are not the whole community.

**Comment by itubetw** [comment]
> You are not the whole community.

But im speaking for them.
